# version: '3.9'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      retries: 5
      timeout: 3s # Health check for Redis  server          
    volumes:
      - redis_data:/data  # Persist Redis data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 448270596903.dkr.ecr.ap-south-1.amazonaws.com/hardware-ecom:latest
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
    # use /infra/dev.env for development
      - ./infra/dev.env  # Use this for local development
    environment:
      DB_HOST: 43.204.143.5
      DB_PORT: 5432
      DB_USER: abhilash
      DB_PASSWORD: kulkarni11
      DB_NAME: ecom
      REDIS_HOST: redis # Use the service name for Redis local development
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

volumes:
  db_data:
  redis_data:
