version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Or remove if you don't need external MySQL access
    environment:
      MYSQL_ROOT_PASSWORD: kulkarni11
      MYSQL_DATABASE: ecom
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 3s

  api:
    image: 448270596903.dkr.ecr.ap-south-1.amazonaws.com/hardware-ecom:latest
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: kulkarni11
      DB_NAME: ecom
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
