version: '3.8'  # Updated version

services:

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose MySQL on 3307
    environment:
      MYSQL_ROOT_PASSWORD: kulkarni11
      MYSQL_DATABASE: ecom
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      timeout: 3s

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db  # Keep 'db' because it's in the same network
      DB_PORT: 3306  # Inside Docker, MySQL runs on 3306
      DB_USER: root
      DB_PASSWORD: kulkarni11
      DB_NAME: ecom
    depends_on:
      db:
        condition: service_healthy  # ✅ Wait until MySQL is fully ready

volumes:
  db_data:
